;
; Ref: http://www.timeanddate.com/library/abbreviations/timezones/
;         http://www.autoitscript.com/forum/topic/47048-scripting-dictionary/
;
; R0    Timothy 12:25 PM 1/8/2014
;

$TimeZoneDictFullToAbbr = ObjCreate("Scripting.Dictionary")
$TimeZoneDictFullToAbbr.CompareMode = 1     ; 0: Binary Mode=case-sensitive, 1: Text Mode=case-insensitive

$TimeZoneDictFullToAbbr.ADD("Australian Central Daylight Time"    , "ACDT" )
$TimeZoneDictFullToAbbr.ADD("Australian Central Standard Time"    , "ACST" )
$TimeZoneDictFullToAbbr.ADD("Atlantic Daylight Time"              , "ADT"  )
$TimeZoneDictFullToAbbr.ADD("Australian Eastern Daylight Time"    , "AEDT" )
$TimeZoneDictFullToAbbr.ADD("Australian Eastern Standard Time"    , "AEST" )
$TimeZoneDictFullToAbbr.ADD("Afghanistan Time"                    , "AFT"  )
$TimeZoneDictFullToAbbr.ADD("Alaska Daylight Time"                , "AKDT" )
$TimeZoneDictFullToAbbr.ADD("Alaska Standard Time"                , "AKST" )
$TimeZoneDictFullToAbbr.ADD("Alma-Ata Time"                       , "ALMT" )
$TimeZoneDictFullToAbbr.ADD("Armenia Summer Time"                 , "AMST" )
$TimeZoneDictFullToAbbr.ADD("Amazon Summer Time"                  , "AMST" )
$TimeZoneDictFullToAbbr.ADD("Armenia Time"                        , "AMT"  )
$TimeZoneDictFullToAbbr.ADD("Amazon Time"                         , "AMT"  )
$TimeZoneDictFullToAbbr.ADD("Anadyr Summer Time"                  , "ANAST")
$TimeZoneDictFullToAbbr.ADD("Anadyr Time"                         , "ANAT" )
$TimeZoneDictFullToAbbr.ADD("Aqtobe Time"                         , "AQTT" )
$TimeZoneDictFullToAbbr.ADD("Argentina Time"                      , "ART"  )
$TimeZoneDictFullToAbbr.ADD("Arabia Standard Time"                , "AST"  )
$TimeZoneDictFullToAbbr.ADD("Atlantic Standard Time"              , "AST"  )
$TimeZoneDictFullToAbbr.ADD("Australian Western Daylight Time"    , "AWDT" )
$TimeZoneDictFullToAbbr.ADD("Australian Western Standard Time"    , "AWST" )
$TimeZoneDictFullToAbbr.ADD("Azores Summer Time"                  , "AZOST")
$TimeZoneDictFullToAbbr.ADD("Azores Time"                         , "AZOT" )
$TimeZoneDictFullToAbbr.ADD("Azerbaijan Summer Time"              , "AZST" )
$TimeZoneDictFullToAbbr.ADD("Azerbaijan Time"                     , "AZT"  )
$TimeZoneDictFullToAbbr.ADD("Brunei Darussalam Time"              , "BNT"  )
$TimeZoneDictFullToAbbr.ADD("Bolivia Time"                        , "BOT"  )
$TimeZoneDictFullToAbbr.ADD("Brasilia Summer Time"                , "BRST" )
$TimeZoneDictFullToAbbr.ADD("Brasília Time"                       , "BRT"  )
$TimeZoneDictFullToAbbr.ADD("Bangladesh Standard Time"            , "BST"  )
$TimeZoneDictFullToAbbr.ADD("British Summer Time"                 , "BST"  )
$TimeZoneDictFullToAbbr.ADD("Bhutan Time"                         , "BTT"  )
$TimeZoneDictFullToAbbr.ADD("Casey Time"                          , "CAST" )
$TimeZoneDictFullToAbbr.ADD("Central Africa Time"                 , "CAT"  )
$TimeZoneDictFullToAbbr.ADD("Cocos Islands Time"                  , "CCT"  )
$TimeZoneDictFullToAbbr.ADD("Cuba Daylight Time"                  , "CDT"  )
$TimeZoneDictFullToAbbr.ADD("Central Daylight Time"               , "CDT"  )
$TimeZoneDictFullToAbbr.ADD("Central European Summer Time"        , "CEST" )
$TimeZoneDictFullToAbbr.ADD("Central European Time"               , "CET"  )
$TimeZoneDictFullToAbbr.ADD("Chatham Island Daylight Time"        , "CHADT")
$TimeZoneDictFullToAbbr.ADD("Chatham Island Standard Time"        , "CHAST")
$TimeZoneDictFullToAbbr.ADD("Cook Island Time"                    , "CKT"  )
$TimeZoneDictFullToAbbr.ADD("Chile Summer Time"                   , "CLST" )
$TimeZoneDictFullToAbbr.ADD("Chile Standard Time"                 , "CLT"  )
$TimeZoneDictFullToAbbr.ADD("Colombia Time"                       , "COT"  )
$TimeZoneDictFullToAbbr.ADD("China Standard Time"                 , "CST"  )
$TimeZoneDictFullToAbbr.ADD("Central Standard Time"               , "CST"  )
$TimeZoneDictFullToAbbr.ADD("Cuba Standard Time"                  , "CST"  )
$TimeZoneDictFullToAbbr.ADD("Cape Verde Time"                     , "CVT"  )
$TimeZoneDictFullToAbbr.ADD("Christmas Island Time"               , "CXT"  )
$TimeZoneDictFullToAbbr.ADD("Chamorro Standard Time"              , "ChST" )
$TimeZoneDictFullToAbbr.ADD("Davis Time"                          , "DAVT" )
$TimeZoneDictFullToAbbr.ADD("Easter Island Summer Time"           , "EASST")
$TimeZoneDictFullToAbbr.ADD("Easter Island Standard Time"         , "EAST" )
$TimeZoneDictFullToAbbr.ADD("Eastern Africa Time"                 , "EAT"  )
$TimeZoneDictFullToAbbr.ADD("East Africa Time"                    , "EAT"  )
$TimeZoneDictFullToAbbr.ADD("Ecuador Time"                        , "ECT"  )
$TimeZoneDictFullToAbbr.ADD("Eastern Daylight Time"               , "EDT"  )
$TimeZoneDictFullToAbbr.ADD("Eastern European Summer Time"        , "EEST" )
$TimeZoneDictFullToAbbr.ADD("Eastern European Time"               , "EET"  )
$TimeZoneDictFullToAbbr.ADD("Eastern Greenland Summer Time"       , "EGST" )
$TimeZoneDictFullToAbbr.ADD("East Greenland Time"                 , "EGT"  )
$TimeZoneDictFullToAbbr.ADD("Eastern Standard Time"               , "EST"  )
$TimeZoneDictFullToAbbr.ADD("Tiempo Del Este"                     , "ET"   )
$TimeZoneDictFullToAbbr.ADD("Fiji Summer Time"                    , "FJST" )
$TimeZoneDictFullToAbbr.ADD("Fiji Time"                           , "FJT"  )
$TimeZoneDictFullToAbbr.ADD("Falkland Islands Summer Time"        , "FKST" )
$TimeZoneDictFullToAbbr.ADD("Falkland Island Time"                , "FKT"  )
$TimeZoneDictFullToAbbr.ADD("Fernando de Noronha Time"            , "FNT"  )
$TimeZoneDictFullToAbbr.ADD("Galapagos Time"                      , "GALT" )
$TimeZoneDictFullToAbbr.ADD("Gambier Time"                        , "GAMT" )
$TimeZoneDictFullToAbbr.ADD("Georgia Standard Time"               , "GET"  )
$TimeZoneDictFullToAbbr.ADD("French Guiana Time"                  , "GFT"  )
$TimeZoneDictFullToAbbr.ADD("Gilbert Island Time"                 , "GILT" )
$TimeZoneDictFullToAbbr.ADD("Greenwich Mean Time"                 , "GMT"  )
$TimeZoneDictFullToAbbr.ADD("Gulf Standard Time"                  , "GST"  )
$TimeZoneDictFullToAbbr.ADD("Guyana Time"                         , "GYT"  )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée de l'Atlantique"       , "HAA"  )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée du Centre"             , "HAC"  )
$TimeZoneDictFullToAbbr.ADD("Hawaii-Aleutian Daylight Time"       , "HADT" )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée de l'Est"              , "HAE"  )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée du Pacifique"          , "HAP"  )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée des Rocheuses"         , "HAR"  )
$TimeZoneDictFullToAbbr.ADD("Hawaii-Aleutian Standard Time"       , "HAST" )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée de Terre-Neuve"        , "HAT"  )
$TimeZoneDictFullToAbbr.ADD("Heure Avancée du Yukon"              , "HAY"  )
$TimeZoneDictFullToAbbr.ADD("Hong Kong Time"                      , "HKT"  )
$TimeZoneDictFullToAbbr.ADD("Hora Legal de Venezuela"             , "HLV"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale de l'Atlantique"       , "HNA"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale du Centre"             , "HNC"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale de l'Est"              , "HNE"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale du Pacifique"          , "HNP"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale des Rocheuses"         , "HNR"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale de Terre-Neuve"        , "HNT"  )
$TimeZoneDictFullToAbbr.ADD("Heure Normale du Yukon"              , "HNY"  )
$TimeZoneDictFullToAbbr.ADD("Hovd Time"                           , "HOVT" )
$TimeZoneDictFullToAbbr.ADD("Indochina Time"                      , "ICT"  )
$TimeZoneDictFullToAbbr.ADD("Israel Daylight Time"                , "IDT"  )
$TimeZoneDictFullToAbbr.ADD("Indian Chagos Time"                  , "IOT"  )
$TimeZoneDictFullToAbbr.ADD("Iran Daylight Time"                  , "IRDT" )
$TimeZoneDictFullToAbbr.ADD("Irkutsk Summer Time"                 , "IRKST")
$TimeZoneDictFullToAbbr.ADD("Irkutsk Time"                        , "IRKT" )
$TimeZoneDictFullToAbbr.ADD("Iran Standard Time"                  , "IRST" )
$TimeZoneDictFullToAbbr.ADD("Israel Standard Time"                , "IST"  )
$TimeZoneDictFullToAbbr.ADD("India Standard Time"                 , "IST"  )
$TimeZoneDictFullToAbbr.ADD("Irish Standard Time"                 , "IST"  )
$TimeZoneDictFullToAbbr.ADD("Japan Standard Time"                 , "JST"  )
$TimeZoneDictFullToAbbr.ADD("Kyrgyzstan Time"                     , "KGT"  )
$TimeZoneDictFullToAbbr.ADD("Krasnoyarsk Summer Time"             , "KRAST")
$TimeZoneDictFullToAbbr.ADD("Krasnoyarsk Time"                    , "KRAT" )
$TimeZoneDictFullToAbbr.ADD("Korea Standard Time"                 , "KST"  )
$TimeZoneDictFullToAbbr.ADD("Kuybyshev Time"                      , "KUYT" )
$TimeZoneDictFullToAbbr.ADD("Lord Howe Daylight Time"             , "LHDT" )
$TimeZoneDictFullToAbbr.ADD("Lord Howe Standard Time"             , "LHST" )
$TimeZoneDictFullToAbbr.ADD("Line Islands Time"                   , "LINT" )
$TimeZoneDictFullToAbbr.ADD("Magadan Summer Time"                 , "MAGST")
$TimeZoneDictFullToAbbr.ADD("Magadan Time"                        , "MAGT" )
$TimeZoneDictFullToAbbr.ADD("Marquesas Time"                      , "MART" )
$TimeZoneDictFullToAbbr.ADD("Mawson Time"                         , "MAWT" )
$TimeZoneDictFullToAbbr.ADD("Mountain Daylight Time"              , "MDT"  )
$TimeZoneDictFullToAbbr.ADD("Mitteleuropäische Sommerzeit"        , "MESZ" )
$TimeZoneDictFullToAbbr.ADD("Mitteleuropäische Zeit"              , "MEZ"  )
$TimeZoneDictFullToAbbr.ADD("Marshall Islands Time"               , "MHT"  )
$TimeZoneDictFullToAbbr.ADD("Myanmar Time"                        , "MMT"  )
$TimeZoneDictFullToAbbr.ADD("Moscow Daylight Time"                , "MSD"  )
$TimeZoneDictFullToAbbr.ADD("Moscow Standard Time"                , "MSK"  )
$TimeZoneDictFullToAbbr.ADD("Mountain Standard Time"              , "MST"  )
$TimeZoneDictFullToAbbr.ADD("Mauritius Time"                      , "MUT"  )
$TimeZoneDictFullToAbbr.ADD("Maldives Time"                       , "MVT"  )
$TimeZoneDictFullToAbbr.ADD("Malaysia Time"                       , "MYT"  )
$TimeZoneDictFullToAbbr.ADD("New Caledonia Time"                  , "NCT"  )
$TimeZoneDictFullToAbbr.ADD("Newfoundland Daylight Time"          , "NDT"  )
$TimeZoneDictFullToAbbr.ADD("Norfolk Time"                        , "NFT"  )
$TimeZoneDictFullToAbbr.ADD("Novosibirsk Summer Time"             , "NOVST")
$TimeZoneDictFullToAbbr.ADD("Novosibirsk Time"                    , "NOVT" )
$TimeZoneDictFullToAbbr.ADD("Nepal Time"                          , "NPT"  )
$TimeZoneDictFullToAbbr.ADD("Newfoundland Standard Time"          , "NST"  )
$TimeZoneDictFullToAbbr.ADD("Niue Time"                           , "NUT"  )
$TimeZoneDictFullToAbbr.ADD("New Zealand Daylight Time"           , "NZDT" )
$TimeZoneDictFullToAbbr.ADD("New Zealand Standard Time"           , "NZST" )
$TimeZoneDictFullToAbbr.ADD("Omsk Summer Time"                    , "OMSST")
$TimeZoneDictFullToAbbr.ADD("Omsk Standard Time"                  , "OMST" )
$TimeZoneDictFullToAbbr.ADD("Pacific Daylight Time"               , "PDT"  )
$TimeZoneDictFullToAbbr.ADD("Peru Time"                           , "PET"  )
$TimeZoneDictFullToAbbr.ADD("Kamchatka Summer Time"               , "PETST")
$TimeZoneDictFullToAbbr.ADD("Kamchatka Time"                      , "PETT" )
$TimeZoneDictFullToAbbr.ADD("Papua New Guinea Time"               , "PGT"  )
$TimeZoneDictFullToAbbr.ADD("Phoenix Island Time"                 , "PHOT" )
$TimeZoneDictFullToAbbr.ADD("Philippine Time"                     , "PHT"  )
$TimeZoneDictFullToAbbr.ADD("Pakistan Standard Time"              , "PKT"  )
$TimeZoneDictFullToAbbr.ADD("Pierre & Miquelon Daylight Time"     , "PMDT" )
$TimeZoneDictFullToAbbr.ADD("Pierre & Miquelon Standard Time"     , "PMST" )
$TimeZoneDictFullToAbbr.ADD("Pohnpei Standard Time"               , "PONT" )
$TimeZoneDictFullToAbbr.ADD("Pacific Standard Time"               , "PST"  )
$TimeZoneDictFullToAbbr.ADD("Pitcairn Standard Time"              , "PST"  )
$TimeZoneDictFullToAbbr.ADD("Tiempo del Pacífico"                 , "PT"   )
$TimeZoneDictFullToAbbr.ADD("Palau Time"                          , "PWT"  )
$TimeZoneDictFullToAbbr.ADD("Paraguay Summer Time"                , "PYST" )
$TimeZoneDictFullToAbbr.ADD("Paraguay Time"                       , "PYT"  )
$TimeZoneDictFullToAbbr.ADD("Reunion Time"                        , "RET"  )
$TimeZoneDictFullToAbbr.ADD("Samara Time"                         , "SAMT" )
$TimeZoneDictFullToAbbr.ADD("South Africa Standard Time"          , "SAST" )
$TimeZoneDictFullToAbbr.ADD("Solomon IslandsTime"                 , "SBT"  )
$TimeZoneDictFullToAbbr.ADD("Seychelles Time"                     , "SCT"  )
$TimeZoneDictFullToAbbr.ADD("Singapore Time"                      , "SGT"  )
$TimeZoneDictFullToAbbr.ADD("Suriname Time"                       , "SRT"  )
$TimeZoneDictFullToAbbr.ADD("Samoa Standard Time"                 , "SST"  )
$TimeZoneDictFullToAbbr.ADD("Tahiti Time"                         , "TAHT" )
$TimeZoneDictFullToAbbr.ADD("French Southern and Antarctic Time"  , "TFT"  )
$TimeZoneDictFullToAbbr.ADD("Tajikistan Time"                     , "TJT"  )
$TimeZoneDictFullToAbbr.ADD("Tokelau Time"                        , "TKT"  )
$TimeZoneDictFullToAbbr.ADD("East Timor Time"                     , "TLT"  )
$TimeZoneDictFullToAbbr.ADD("Turkmenistan Time"                   , "TMT"  )
$TimeZoneDictFullToAbbr.ADD("Tuvalu Time"                         , "TVT"  )
$TimeZoneDictFullToAbbr.ADD("Ulaanbaatar Time"                    , "ULAT" )
$TimeZoneDictFullToAbbr.ADD("Universal Time Coordinated"          , "UTC"  )
$TimeZoneDictFullToAbbr.ADD("Uruguay Summer Time"                 , "UYST" )
$TimeZoneDictFullToAbbr.ADD("Uruguay Time"                        , "UYT"  )
$TimeZoneDictFullToAbbr.ADD("Uzbekistan Time"                     , "UZT"  )
$TimeZoneDictFullToAbbr.ADD("Venezuelan Standard Time"            , "VET"  )
$TimeZoneDictFullToAbbr.ADD("Vladivostok Summer Time"             , "VLAST")
$TimeZoneDictFullToAbbr.ADD("Vladivostok Time"                    , "VLAT" )
$TimeZoneDictFullToAbbr.ADD("Vanuatu Time"                        , "VUT"  )
$TimeZoneDictFullToAbbr.ADD("West Africa Summer Time"             , "WAST" )
$TimeZoneDictFullToAbbr.ADD("West Africa Time"                    , "WAT"  )
$TimeZoneDictFullToAbbr.ADD("Western European Summer Time"        , "WEST" )
$TimeZoneDictFullToAbbr.ADD("Westeuropäische Sommerzeit"          , "WESZ" )
$TimeZoneDictFullToAbbr.ADD("Western European Time"               , "WET"  )
$TimeZoneDictFullToAbbr.ADD("Westeuropäische Zeit"                , "WEZ"  )
$TimeZoneDictFullToAbbr.ADD("Wallis and Futuna Time"              , "WFT"  )
$TimeZoneDictFullToAbbr.ADD("Western Greenland Summer Time"       , "WGST" )
$TimeZoneDictFullToAbbr.ADD("West Greenland Time"                 , "WGT"  )
$TimeZoneDictFullToAbbr.ADD("Western Indonesian Time"             , "WIB"  )
$TimeZoneDictFullToAbbr.ADD("Eastern Indonesian Time"             , "WIT"  )
$TimeZoneDictFullToAbbr.ADD("Central Indonesian Time"             , "WITA" )
$TimeZoneDictFullToAbbr.ADD("Western Sahara Summer Time"          , "WST"  )
$TimeZoneDictFullToAbbr.ADD("West Samoa Time"                     , "WST"  )
$TimeZoneDictFullToAbbr.ADD("Western Sahara Standard Time"        , "WT"   )
$TimeZoneDictFullToAbbr.ADD("Yakutsk Summer Time"                 , "YAKST")
$TimeZoneDictFullToAbbr.ADD("Yakutsk Time"                        , "YAKT" )
$TimeZoneDictFullToAbbr.ADD("Yap Time"                            , "YAPT" )
$TimeZoneDictFullToAbbr.ADD("Yekaterinburg Summer Time"           , "YEKST")
$TimeZoneDictFullToAbbr.ADD("Yekaterinburg Time"                  , "YEKT" )


Func TimeZoneDictFullToAbbr($FullName)
    If $TimeZoneDictFullToAbbr.Exists($FullName) Then
        return $TimeZoneDictFullToAbbr($FullName)
    Else
        return ""
    EndIf
EndFunc

;MsgBox(0, "Pacific Standard Time", TimeZoneDictFullToAbbr("Pacific Standard Time"))
;MsgBox(0, "pacific standard time", TimeZoneDictFullToAbbr("pacific standard time"))
;MsgBox(0, "Count", $TimeZoneDictFullToAbbr.Count)
;MsgBox(0, "CompareMode", $TimeZoneDictFullToAbbr.CompareMode)